clone:
  default:
    image: plugins/git
    recursive: false

pipeline:
  build:
    image: dunecommunity/gitlabci_dockerindocker-dockerindocker
    commands:
      - BHOST=$(hostname -i | awk '{ print $1 }')
      - echo $DOCKER_PW | docker login --username="$DOCKER_USER" --password-stdin
      - pip3 install -U bottle docker
      - .ci/docker/update_image.py "$CC" "$BHOST" "$ZIVGITLAB_TOKEN"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [ zivgitlab_token, docker_user, docker_pw ]

  notify:
    image: drillster/drone-email
    host: mail.milk.pm
    from: drone@pymor.org
    when:
      status: [ changed, failure ]
    secrets:  [ email_username, email_password ]

matrix:
  CC:
    - gcc
    - clang

ports:
 - "17777"
